services:
  api:
    container_name: prayhelper-server
    build:
      context: .
      dockerfile: Dockerfile
    image: prayhelper:latest
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app
      APP_CONFIG_FILE: config/production.py
      FLASK_DEBUG: "true"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DOCKER_DEFAULT_PLATFORM: linux/amd64
      TZ: "Asia/Seoul"
    command: ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
    