services:
  api:
    container_name: prayhelper-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app
      APP_CONFIG_FILE: config/production.py
      FLASK_DEBUG: "true"
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
    command: ["python3", "-m", "flask", "run", "--host=0.0.0.0"]

  db:
    container_name: prayhelper-database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    image: postgres:latest
    networks:
      - default
    ports:
      - "5432:5432"
    restart: always