services:
  api:
    container_name: prayhelper-server-dev
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    image: prayhelper-server-prod
    ports:
      - "4002:5000"
    volumes:
      - ../:/app
    environment:
      FLASK_APP: app
      APP_CONFIG_FILE: config/production.py
      FLASK_DEBUG: false
    command: ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
    