name: Deploy Backend on Development Server
on:
  push:
    branches:
      - feature/cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Remove Conflictable Files
        run: |
          if [ -f Dockerfile ]; then
            rm Dockerfile
          fi
          if [ -f docker-compose.yml ]; then
            rm docker-compose.yml
          fi

      - name: Send
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "."
          target: ${{ secrets.PATH }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            ./run.sh
